use std::error::Error;

#[cfg(target_os = "windows")]
pub fn register_context_menus() -> Result<(), Box<dyn Error>> {
    use windows_registry::CURRENT_USER;

    let exe_path = std::env::current_exe()?;
    let exe_path_str = exe_path.to_string_lossy();
    // Use double quotes for the path to handle spaces.
    // %1 is the placeholder for the file/folder path.
    let command = format!("\"{}\" \"%1\"", exe_path_str);
    let command_here = format!("\"{}\" \".\"", exe_path_str);

    // File Context Menu: Right-click on any file.
    let file_key = CURRENT_USER.create("Software\\Classes\\*\\shell\\AltaiApp")?;
    file_key.set_string("", "Open with Altai App")?;
    file_key.set_string("Icon", &exe_path_str)?;
    let file_command_key = file_key.create("command")?;
    file_command_key.set_string("", &command)?;

    // Folder Context Menu: Right-click on a folder.
    let folder_key = CURRENT_USER.create("Software\\Classes\\Directory\\shell\\AltaiApp")?;
    folder_key.set_string("", "Open Folder with Altai App")?;
    folder_key.set_string("Icon", &exe_path_str)?;
    let folder_command_key = folder_key.create("command")?;
    folder_command_key.set_string("", &command)?;

    // Background Context Menu: Right-click inside a folder.
    let bg_key = CURRENT_USER.create("Software\\Classes\\Directory\\Background\\shell\\AltaiApp")?;
    bg_key.set_string("", "Open Altai App Here")?;
    bg_key.set_string("Icon", &exe_path_str)?;
    let bg_command_key = bg_key.create("command")?;
    bg_command_key.set_string("", &command_here)?;

    // AI Context Menus for Files
    let explain_key = CURRENT_USER.create("Software\\Classes\\*\\shell\\AltaiAppExplain")?;
    explain_key.set_string("", "Explain with Altai App")?;
    explain_key.set_string("Icon", &exe_path_str)?;
    let explain_command_key = explain_key.create("command")?;
    explain_command_key.set_string("", format!("\"{}\" --explain \"%1\"", exe_path_str))?;

    let refactor_key = CURRENT_USER.create("Software\\Classes\\*\\shell\\AltaiAppRefactor")?;
    refactor_key.set_string("", "Refactor with Altai App")?;
    refactor_key.set_string("Icon", &exe_path_str)?;
    let refactor_command_key = refactor_key.create("command")?;
    refactor_command_key.set_string("", format!("\"{}\" --refactor \"%1\"", exe_path_str))?;

    // Folder Context Menu: Ask About Project
    let project_key = CURRENT_USER.create("Software\\Classes\\Directory\\shell\\AltaiAppProject")?;
    project_key.set_string("", "Ask Altai App About This Project")?;
    project_key.set_string("Icon", &exe_path_str)?;
    let project_command_key = project_key.create("command")?;
    project_command_key.set_string("", format!("\"{}\" --ask-project \"%1\"", exe_path_str))?;

    Ok(())
}

#[cfg(not(target_os = "windows"))]
pub fn register_context_menus() -> Result<(), Box<dyn Error>> {
    // macOS and Linux usually handle this via .app bundles or .desktop files
    // which are generated by the installer/packager.
    Ok(())
}
